'''
Construct an extended module
'''
class ExtendedModule:
    def __init__(self,)

''' 
Input:
    - n : integer, number of vertices in the Nakayama algebra
    - relations : list of relations, optional, default is an empty list
        relations are on the form of tuples (i,j) with i<=j representing the path from vertex i to vertex j
This class represents a linear Nakayama algebra A_n=kQ/R where
Q := 1 -(v1)-> 2 -(v2)-> ... -(v_{n-1})-> n
and R is the ideal generated by the relations.  
'''
class NakayamaAlgebra:
    def __init__(self,n,relations=None);
        self.n=n
        self.relations=relations if relations is not None else []